name: Set up Project Dependencies
description: Download and install dependencies and libraries used by the project.

inputs:
  platform:
    required: true
  gdsion-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install rcedit (Windows)
      if: ${{ inputs.platform == 'windows' }}
      shell: bash
      run: |
        curl -JLO https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe
        mv rcedit-x64.exe rcedit.exe
        export PATH=$(realpath ./):$PATH

    - name: Install GDSiON
      shell: bash
      env:
        GDSION_PATH: https://github.com/YuriSizov/gdsion/releases/download/${{ inputs.gdsion-version }}/libgdsion-${{ inputs.platform }}.zip
      run: |
        curl -JLO ${{ env.GDSION_PATH }}
        unzip libgdsion-${{ inputs.platform }}.zip
    
    # Web platform is exported via Linux, so install that version of GDSiON as well.
    - name: Install GDSiON Linux (Web)
      if: ${{ inputs.platform == 'web' }}
      shell: bash
      env:
        GDSION_PATH: https://github.com/YuriSizov/gdsion/releases/download/${{ inputs.gdsion-version }}/libgdsion-linux.zip
      run: |
        curl -JLO ${{ env.GDSION_PATH }}
        unzip -n libgdsion-linux.zip
